### PR TITLE
fix: make partial property text regex work

### LINKED ISSUE #113: Find element by partial text (RegEx support for text property)
Hi,
does WDI5 support matching elements by partial text, or RegExpr in the text property?

Our Use Case is: Find elements contaning "Salatteller" text  on a given UI5 page.

Details of use case:
We POC a migration from UIVeri5 to WDI5.
We have data created by API with timestamps (like "UIVERI5_AUTO SAP-Style-Salatteller mit Spinat Maultaschen 2021-12-01T12:23:49.444Z"), so we use a lot of partial matching in our tests.

On UIVeri5, we were using following locator:
``` js
   var title = element(by.control({
      controlType: 'sap.m.Title',
      properties: {
         text: new RegExp(text)
      }
   }));
```

This seems not to work on wdi5 :
``` js
const title = browser.asControl({
    selector: {
        controlType: 'sap.m.Title',
        properties: {
              text: new RegExp(text)
        }
    }
});
```

Thanks,
Adrianna

### PR DESCRIPTION
**Pull request by vobu**
closes #113

### CODE REVIEW

File: wdio-ui5-service/src/lib/WDI5.js [hunk 1]
```diff
@@ -579,6 +579,30 @@ module.exports = class WDI5 {
             // further processing there
             controlSelector.selector.id = controlSelector.selector.id.toString();
         }
+
+        // check whether we have a (partial) text matcher
+        // that should match:
+        // properties: {
+        //     text: new RegExp(/.*ersi.*/gm)
+        // }
+        // ...but not:
```
Comment (dominikfeininger) [inline wdio-ui5-service/src/lib/WDI5.js:588]: Suggestion: Add comment or or README for declarative matcher in UI5 version < 1.74.

**Comment by dominikfeininger** [comment]
LGTM.
