### PR TITLE
fix(aggregation): shorthand access for index 0

### LINKED ISSUE #124: inconsistent behaviour in get$Shorthand (getItems, getContent, etc.)
Very annoying bug if you want to the the first entry as WDI5 object of an aggregation - it isn't possible at the moment.

If I call getContent(0) on a sap.m.Page WDI5 object, I get an array of objects each containing the attribute 'id'. This is the same behavior as getContent(true).
If I call getContent(1) I would get the WDI5 object. Please fix this bug or make an exception in the README.md (or is it documented?)

I previously thought this could be related to webdriver/sync and stuff. I know the value '0' is considered as falsy, but as argument you could easily compare the input type and concrete value.

**Runtime Env (please complete the following information):**
- `wdi5/wdio-ui5-service`- 0.8.1
- `UI5` version: 1.71.41
- `wdio`-version (output of `wdio --version`): 7.16.14
- `node`-version (output of `node --version`): v16.13.2
 - OS: Mac OS X
 - Browser + Version: chrome 97.0.4692.99

### PR DESCRIPTION
**Pull request by vobu**
fixing unintended side effects of get$Shorthand(0) -
get$Shorthand(1..n) worked fine!

closes #124

### CODE REVIEW

File: wdio-ui5-service/src/lib/WDI5.js [hunk 1]
```diff
@@ -309,11 +309,12 @@ module.exports = class WDI5 {
                 // return result on array index 1 anyways
                 return result[1];
             case 'aggregation': // also applies for getAggregation convenience methods such as $ui5control.getItems()
-                // check weather to retrieve all elements in the aggreation as ui5 control
+                // check weather to retrieve all elements in the aggreation as ui5 controls
                 if ((args.length > 0 && typeof args[0] === 'boolean' && args[0] === false) || args.length === 0) {
                     // get all if param is false or undefined
                     return await this._retrieveElements(result[1]);
-                } else if (args[0] && typeof args[0] === 'number') {
+                } else if (String(args[0]) && typeof args[0] === 'number') {
```
Comment (BeastiW) [inline wdio-ui5-service/src/lib/WDI5.js:316]: Hi @vobu,
I guess `typeof args[0] === 'number'` would be perfectly sufficient and fine. What else do you want to accomplish by `String(args[0])`?

**Comment by dominikfeininger** [comment]
lgtm ;)

File: wdio-ui5-service/src/lib/WDI5.js (hunk 1 above)
Comment (vobu) [reply wdio-ui5-service/src/lib/WDI5.js:316]: yep, probably, but given the TS rewrite is under way (pssst, spoilerz 🤫), this will find its' way in by natural causes (stricter typing) 😄
