### PR TITLE
fix(auth): throw error when auth env vars are missing

### LINKED ISSUE #695: Authentication error handling needs improvement
When using built-in BTP authentication in wdi5, misconfiguration (like missing username or incorrect IDP domain/environment variable names) leads to unclear or generic error messages. This makes it difficult to identify that the issue is with the authentication setup rather than the test or application.

**Current Behavior**

If authentication is misconfigured (e.g. missing username, wrong IDP domain, incorrect environment variable names), wdi5 throws an error which does not specify what is misconfigured -
`ERROR @wdio/utils:shim: Error: Can't call setValue on element with selector "#j_password" because element wasn't found`
As a new user, it took me a while to realize that the issue was due to missing authentication parameters (I was trying BTP authentication)

**Expected Behavior**

wdi5 should validate authentication configuration before starting tests and based on the config provide descriptive and actionable error messages when required fields (like username or idp domain) are missing.

### PR DESCRIPTION
**Pull request by chetan2332**
This PR fixes #695

### CODE REVIEW

File: src/lib/authentication/Authenticator.ts [hunk 1]
```diff
@@ -19,15 +19,23 @@ export default class Authenticator {
         if (browser.isMultiremote) {
             envName = `wdi5_${this.browserInstanceName}_username`
         }
-        return process.env[envName] || ""
+        const sUserName = process.env[envName]
```
Comment (mauriciolauffer) [inline src/lib/authentication/Authenticator.ts]: No Hungarian notation, please.

**Comment by mauriciolauffer** [comment]
@chetan2332 tests added. Thanks :)
